/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hotel.managment.View.AdminView;

import java.awt.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/**
 *
 * @author admin
 */
public class HomeAdmin extends javax.swing.JFrame {

    
     Color paneldefault;
     Color click;
    
       public <T> void print(T s){
         System.out.println(s);
      }
      public <T> void show(T s){
        JOptionPane.showMessageDialog(null,s);
      }
    
     public void resetdefault(){
       this.home_tab.setColorNormal(this.paneldefault);
        this.user_tab.setColorNormal(this.paneldefault);
        this.booking_tab.setColorNormal(this.paneldefault);
        this.room_tab.setColorNormal(this.paneldefault);
        this.employee_tab.setColorNormal(this.paneldefault);
     }
     
    
    public HomeAdmin() throws ClassNotFoundException, SQLException {
        initComponents();
        paneldefault = new Color(240,240 ,240);
        click = new Color(255,255,255);
        
 
        
        menu1 menu = new menu1();
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(menu).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        home_tab = new rojeru_san.complementos.RSButtonPane();
        jLabel2 = new javax.swing.JLabel();
        room_tab = new rojeru_san.complementos.RSButtonPane();
        jLabel3 = new javax.swing.JLabel();
        booking_tab = new rojeru_san.complementos.RSButtonPane();
        jLabel4 = new javax.swing.JLabel();
        employee_tab = new rojeru_san.complementos.RSButtonPane();
        jLabel5 = new javax.swing.JLabel();
        user_tab = new rojeru_san.complementos.RSButtonPane();
        jLabel6 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(73, 135, 229));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Admin");

        home_tab.setBackground(new java.awt.Color(255, 255, 255));
        home_tab.setColorHover(new java.awt.Color(73, 135, 229));
        home_tab.setColorNormal(new java.awt.Color(255, 255, 255));
        home_tab.setPreferredSize(new java.awt.Dimension(186, 66));
        home_tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_tabMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Home");

        javax.swing.GroupLayout home_tabLayout = new javax.swing.GroupLayout(home_tab);
        home_tab.setLayout(home_tabLayout);
        home_tabLayout.setHorizontalGroup(
            home_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_tabLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        home_tabLayout.setVerticalGroup(
            home_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_tabLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        room_tab.setColorHover(new java.awt.Color(73, 135, 229));
        room_tab.setColorNormal(new java.awt.Color(240, 240, 240));
        room_tab.setPreferredSize(new java.awt.Dimension(186, 66));
        room_tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                room_tabMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Room");

        javax.swing.GroupLayout room_tabLayout = new javax.swing.GroupLayout(room_tab);
        room_tab.setLayout(room_tabLayout);
        room_tabLayout.setHorizontalGroup(
            room_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(room_tabLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel3)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        room_tabLayout.setVerticalGroup(
            room_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(room_tabLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        booking_tab.setColorHover(new java.awt.Color(73, 135, 229));
        booking_tab.setColorNormal(new java.awt.Color(240, 240, 240));
        booking_tab.setPreferredSize(new java.awt.Dimension(186, 66));
        booking_tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booking_tabMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("booking");

        javax.swing.GroupLayout booking_tabLayout = new javax.swing.GroupLayout(booking_tab);
        booking_tab.setLayout(booking_tabLayout);
        booking_tabLayout.setHorizontalGroup(
            booking_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booking_tabLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel4)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        booking_tabLayout.setVerticalGroup(
            booking_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booking_tabLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        employee_tab.setColorHover(new java.awt.Color(73, 135, 229));
        employee_tab.setColorNormal(new java.awt.Color(240, 240, 240));
        employee_tab.setPreferredSize(new java.awt.Dimension(186, 66));
        employee_tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employee_tabMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Employees");

        javax.swing.GroupLayout employee_tabLayout = new javax.swing.GroupLayout(employee_tab);
        employee_tab.setLayout(employee_tabLayout);
        employee_tabLayout.setHorizontalGroup(
            employee_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employee_tabLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel5)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        employee_tabLayout.setVerticalGroup(
            employee_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employee_tabLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        user_tab.setColorHover(new java.awt.Color(73, 135, 229));
        user_tab.setColorNormal(new java.awt.Color(240, 240, 240));
        user_tab.setPreferredSize(new java.awt.Dimension(186, 66));
        user_tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_tabMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Users");

        javax.swing.GroupLayout user_tabLayout = new javax.swing.GroupLayout(user_tab);
        user_tab.setLayout(user_tabLayout);
        user_tabLayout.setHorizontalGroup(
            user_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_tabLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        user_tabLayout.setVerticalGroup(
            user_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_tabLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel13)
                .addContainerGap(101, Short.MAX_VALUE))
            .addComponent(home_tab, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
            .addComponent(room_tab, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
            .addComponent(booking_tab, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
            .addComponent(employee_tab, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
            .addComponent(user_tab, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel13)
                .addGap(101, 101, 101)
                .addComponent(home_tab, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(room_tab, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(booking_tab, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employee_tab, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_tab, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 902, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void home_tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_tabMouseClicked
         try {
             // TODO add your handling code here:
             menu1 menu = new menu1();
             this.jDesktopPane1.removeAll();
             this.jDesktopPane1.add(menu).setVisible(true);
             resetdefault();
             this.home_tab.setColorNormal(click);
         } catch (ClassNotFoundException ex) {
             print(ex);
         } catch (SQLException ex) {
             print(ex);
         }
        
    }//GEN-LAST:event_home_tabMouseClicked

    private void room_tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_room_tabMouseClicked
         try {
             // TODO add your handling code here:
             menu2 menu = new menu2();
             this.jDesktopPane1.removeAll();
             this.jDesktopPane1.add(menu).setVisible(true);
             resetdefault();
             this.room_tab.setColorNormal(click);
         } catch (ClassNotFoundException ex) {
            print(ex);
         } catch (SQLException ex) {
             print(ex);
         }
    }//GEN-LAST:event_room_tabMouseClicked

    private void booking_tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booking_tabMouseClicked
        // TODO add your handling code here:
        menu4 menu = null;
         try {
             menu = new menu4();
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(HomeAdmin.class.getName()).log(Level.SEVERE, null, ex);
         } catch (SQLException ex) {
             Logger.getLogger(HomeAdmin.class.getName()).log(Level.SEVERE, null, ex);
         }
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(menu).setVisible(true);
        resetdefault();
        this.booking_tab.setColorNormal(click);
    }//GEN-LAST:event_booking_tabMouseClicked

    private void employee_tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employee_tabMouseClicked
        // TODO add your handling code here:
                 menu5 menu = null;
         try {
             menu = new menu5();
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(HomeAdmin.class.getName()).log(Level.SEVERE, null, ex);
         } catch (SQLException ex) {
             Logger.getLogger(HomeAdmin.class.getName()).log(Level.SEVERE, null, ex);
         }
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(menu).setVisible(true);
        resetdefault();
        this.employee_tab.setColorNormal(click);
    }//GEN-LAST:event_employee_tabMouseClicked

    private void user_tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_tabMouseClicked
        // TODO add your handling code here:
                 menu3 menu = new menu3();
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(menu).setVisible(true);
        resetdefault();
        this.user_tab.setColorNormal(click);
    }//GEN-LAST:event_user_tabMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HomeAdmin().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    System.out.println(ex);
                } catch (SQLException ex) {
                     System.out.println(ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSButtonPane booking_tab;
    private rojeru_san.complementos.RSButtonPane employee_tab;
    private rojeru_san.complementos.RSButtonPane home_tab;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private rojeru_san.complementos.RSButtonPane room_tab;
    private rojeru_san.complementos.RSButtonPane user_tab;
    // End of variables declaration//GEN-END:variables
}
